# This is a basic workflow to help you get started with Actions

name: Lighthouse CI score

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [lighthouse]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.15.1'
      - uses: browser-actions/setup-chrome@v1
      - name: Install Lighthouse CLI
        run: npm install -g @lhci/cli

      - name: Running Lighthouse
        run: lhci autorun

      - name: Comparing value of current request with qa and preprod
        run: node compare.js
      
      - name: test hello
        run: node hello.js
      
      - name: test abc
        run: node abc.js
      
      - name: test directory
        run: ls
